### ISSUE TITLE
Cant able to run the project

### ISSUE THREAD

**Issue by Sayak-Mallick** [abhibagul/Wix-Clone#1]
It is showing this kind of error sir, kindly tell me what should I do so that it will run succesfully. 

backend@1.0.0 dev /projects/novac-side-projects/novac-builder/backend
> nodemon --exec babel-node -r dotenv/config ./src/server.js

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `babel-node -r dotenv/config ./src/server.js`
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '/projects/novac-side-projects/novac-builder/backend/dotenv/config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at Object.<anonymous> (/projects/novac-side-projects/novac-builder/backend/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by abhibagul** [comment]
You need to  `cd backend/` and install dependencies. Seems like [dotenv ](https://www.npmjs.com/package/dotenv) is not installed.  Try `npm install -y`

**Comment by Sayak-Mallick** [comment]
@abhibagul can you provide the screenshot of the  folder structure of your backend because it is showing this problem

[nodemon] starting `babel-node -r dotenv/config ./src/server.js`
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '/projects/novac-side-projects/Wix-Clone/backend/dotenv/config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at Object.<anonymous> (/projects/novac-side-projects/Wix-Clone/backend/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

i did whatever you told me to do but still i am getting this above error

**Comment by abhibagul** [comment]
Have you created the `.env` file? Although, the issue still seems to me about [dependencies not getting installed properly](https://stackoverflow.com/questions/61407393/while-running-the-script-throws-cannot-find-module-dotenv). 

Also, make sure you are starting server as `npm run dev`

**Comment by Sayak-Mallick** [comment]
Yes sir i have created the .env file in the directory and also completed all the procedures listed by you. Also i have tried to start the server using npm run dev.

**Comment by abhibagul** [comment]
Please share your `.env` file also open `backend/src/db.js` 

and replace the line 6 with,
`client = await MongoClient.connect( "mongodb://localhost:27017", {`

**Comment by Sayak-Mallick** [comment]
@abhibagul it is showing this error

Error: Cannot find module '/projects/novac-side-projects/Novac-Builder/Wix-Clone/backend/dotenv/config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at Object.<anonymous> (/projects/novac-side-projects/Novac-Builder/Wix-Clone/backend/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

**Comment by Sayak-Mallick** [comment]
here is my .env file

JWT_SECRET=""
PORT=8000
API_LOGIN_PERIOD="2d"

**Comment by Sayak-Mallick** [comment]
@abhibagul  i ahve also replaced the line 6 with,
client = await MongoClient.connect( "mongodb://localhost:27017", {

**Comment by abhibagul** [comment]
Make the env file like this. Make sure you have MongoDB installed on your system.
```
JWT_SECRET="abcdefghijklmnzwqutkjdlndfldf"
PORT=8000
API_DB_NAME="wixclonedb"
API_LOGIN_PERIOD="2d"
```

**Comment by Sayak-Mallick** [comment]
Okk sir thanks for your help
